import type { Metadata } from "next";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { RESUME, type Bullet } from "@/lib/resumeData";

export const metadata: Metadata = {
  title: "Resume",
  description: `${RESUME.name} — ${RESUME.title}, ${RESUME.location}.`,
  alternates: { canonical: "/resume" },
};

/** One rendering for two surfaces: the public web page, and the PDF
 *  (generated by scripts/build-resume-pdf.mjs hitting /resume?pdf=1 —
 *  pdf mode drops site chrome; the script injects the phone number so
 *  it never enters this public repo). */

function Evidence({ b }: { b: Bullet }) {
  if (b.filmId)
    return (
      <a
        href={`https://daeseon.ai/portfolio#${b.filmId}`}
        className="whitespace-nowrap text-[10.5px] font-semibold text-sky-700 print:text-sky-800"
      >
        {" ▶ case film"}
      </a>
    );
  if (b.deepDive)
    return (
      <a
        href={`https://faangforge.daeseon.ai/story/${b.deepDive}`}
        className="whitespace-nowrap text-[10.5px] font-semibold text-sky-700 print:text-sky-800"
      >
        {" » deep-dive"}
      </a>
    );
  return null;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-2">
      <h2 className="border-b border-neutral-300 pb-0.5 text-[10.5px] font-bold uppercase tracking-[0.12em] text-neutral-800">
        {title}
      </h2>
      <div className="mt-1">{children}</div>
    </section>
  );
}

export default async function ResumePage({
  searchParams,
}: {
  searchParams: Promise<{ pdf?: string }>;
}) {
  const pdfMode = (await searchParams).pdf === "1";
  const r = RESUME;
  return (
    <>
      {!pdfMode && <Header locale="en" currentPath="/resume" />}
      <style>{`@page { size: Letter; margin: 9mm 11mm; } @media print { body { background: #fff !important; } }`}</style>

      <main
        className={`mx-auto max-w-[8in] bg-white px-6 text-neutral-900 print:max-w-none print:px-0 ${pdfMode ? "py-2" : "my-8 rounded-xl border border-neutral-200 py-8 shadow-sm print:my-0 print:rounded-none print:border-0 print:py-0 print:shadow-none"}`}
      >
        {/* Head */}
        <header className="text-center">
          <h1 className="text-[20px] font-bold">{r.name}</h1>
          <p className="mt-0.5 text-[11.5px] leading-snug text-neutral-700">
            {r.title} · <b>{r.authorization}</b> · {r.location}
            <span id="phone-slot" />
            {" · "}
            <a className="text-sky-700" href={`mailto:${r.email}`}>
              {r.email}
            </a>
            {" · "}
            <a className="text-sky-700" href={r.links.linkedin}>
              LinkedIn
            </a>
            {" · "}
            <a className="text-sky-700" href={r.links.github}>
              GitHub
            </a>
            {" · "}
            <a className="text-sky-700" href={r.links.blog}>
              Blog
            </a>
            {" · "}
            <a className="text-sky-700" href={r.links.portfolio}>
              Portfolio
            </a>
          </p>
        </header>

        <Section title="Professional Summary">
          <p className="text-[11px] leading-[1.3]">{r.summary}</p>
        </Section>

        <Section title="Technical Skills">
          <ul className="space-y-px text-[11px] leading-[1.3]">
            {r.skills.map((s) => (
              <li key={s.group}>
                <b>{s.group}:</b> {s.items}
              </li>
            ))}
          </ul>
        </Section>

        <Section title="Work Experience">
          {r.experience.map((e) => (
            <div key={e.company} className="mb-1">
              <div className="flex items-baseline justify-between">
                <p className="text-[12px]">
                  <b>{e.role}</b> · {e.company}
                </p>
                <p className="text-[11.5px] font-semibold text-neutral-700">{e.period}</p>
              </div>
              <ul className="mt-0.5 list-disc space-y-[2px] pl-4 text-[11px] leading-[1.3]">
                {e.bullets.map((b) => (
                  <li key={b.text.slice(0, 40)}>
                    {b.text}
                    <Evidence b={b} />
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </Section>

        <Section title="Selected Projects">
          {r.projects.map((p) => (
            <div key={p.name} className="mb-1">
              <p className="text-[12px]">
                <b>{p.name}</b> — {p.tagline} · <span className="text-neutral-600">{p.stack}</span>
              </p>
              <ul className="mt-0.5 list-disc space-y-[2px] pl-4 text-[11px] leading-[1.3]">
                {p.bullets.map((b) => (
                  <li key={b.text.slice(0, 40)}>
                    {b.text}
                    <Evidence b={b} />
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </Section>

        <Section title="Education">
          <div className="flex items-baseline justify-between text-[12px]">
            <p>
              <b>{r.education.degree}</b> — {r.education.school}
            </p>
            <p className="text-[11.5px] font-semibold text-neutral-700">{r.education.period}</p>
          </div>
        </Section>
      </main>

      {!pdfMode && (
        <div className="print:hidden">
          <Footer locale="en" />
        </div>
      )}
    </>
  );
}
